spring:
  profiles:
    active: smart
  application:
    name: Logosztics
  thymeleaf:
    cache: false
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://192.168.0.61:5432/cubixlogosztics
    username: webuser
    password: psoestrg
server:
  port: 8081
logosztics:
  jwtData:
    issuer: LgApp
    alg: HMAC512
    secret: mysecret
    duration: 10m